
name: Update - Footballdata 12Xpert (2019/20,2020,2020/21) datasets

on:
  schedule:
    # note: * is a special character in YAML so you have to quote this string
    #  see cron guru for more examples / help on syntax
    #    ->  https://crontab.guru/examples.html
#    - cron:  '0 4 * * FRI'       #  every Friday at 4 am (utc?)
    - cron:  '0 8 * * MON'       #  every Monday at 8 am (utc?)
  workflow_dispatch:
    ### for testing / debugging allow "manual" start


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.

    - name: Run install / adduser
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        bundle install
        yo -f ./workflow/footballdata/Flowfile.rb adduser

    - name: Run ssh_clone
      run:  yo -f ./workflow/footballdata/Flowfile.rb clone

    - name: Run download
      run:  yo -r footballdata-12xpert -f ./workflow/footballdata/Flowfile.rb download

    - name: Run convert
      run:  yo -r footballdata-12xpert -f ./workflow/footballdata/Flowfile.rb convert

    - name: Run ssh_push
      run:  yo -f ./workflow/footballdata/Flowfile.rb push

