
name: Stage - Footballdata (2020) datasets

on:
  schedule:
    # note: * is a special character in YAML so you have to quote this string
    #  see cron guru for more examples / help on syntax
    #    ->  https://crontab.guru/examples.html
#    - cron:  '0 4 * * FRI'       #  every Friday at 4 am (utc?)
    - cron:  '0 3 * * TUE'       #  every Tuesday at 3 am (utc?)
  workflow_dispatch:
    ### for testing / debugging allow "manual" start


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.

    - name: setup
      run: |
        bundle install
        yo -f ./workflow/stage/setup.rb setup

    - name: Run setup / ssh_clone
      run:  yo -f ./workflow/stage/setup.rb clone

    - name: Run download
      env:
        FOOTBALLDATA: ${{ secrets.FOOTBALLDATA }}
      run:  yo -f ./workflow/stage/1_top_2020.rb download

    - name: Run convert
      run:  yo -f ./workflow/stage/1_top_2020.rb convert

    - name: Run ssh_push
      run:  yo -f ./workflow/stage/setup.rb push

